/*
Turbot Pipes

Turbot Pipes is an intelligence, automation & security platform built specifically for DevOps.

API version: {{OPEN_API_VERSION}}
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipes

import (
	"encoding/json"
	"fmt"
)

// ConnectionStatus the model 'ConnectionStatus'
type ConnectionStatus string

// List of ConnectionStatus
const (
	ConnectionStatusEnabled  ConnectionStatus = "enabled"
	ConnectionStatusDisabled ConnectionStatus = "disabled"
)

// All allowed values of ConnectionStatus enum
var AllowedConnectionStatusEnumValues = []ConnectionStatus{
	"enabled",
	"disabled",
}

func (v *ConnectionStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ConnectionStatus(value)
	for _, existing := range AllowedConnectionStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ConnectionStatus", value)
}

// NewConnectionStatusFromValue returns a pointer to a valid ConnectionStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConnectionStatusFromValue(v string) (*ConnectionStatus, error) {
	ev := ConnectionStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConnectionStatus: valid values are %v", v, AllowedConnectionStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConnectionStatus) IsValid() bool {
	for _, existing := range AllowedConnectionStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ConnectionStatus value
func (v ConnectionStatus) Ptr() *ConnectionStatus {
	return &v
}

type NullableConnectionStatus struct {
	value *ConnectionStatus
	isSet bool
}

func (v NullableConnectionStatus) Get() *ConnectionStatus {
	return v.value
}

func (v *NullableConnectionStatus) Set(val *ConnectionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionStatus(val *ConnectionStatus) *NullableConnectionStatus {
	return &NullableConnectionStatus{value: val, isSet: true}
}

func (v NullableConnectionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
