/*
Turbot Pipes

Turbot Pipes is an intelligence, automation & security platform built specifically for DevOps.

API version: {{OPEN_API_VERSION}}
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipes

import (
	"encoding/json"
)

// WorkspaceNotifierCommandResponse struct for WorkspaceNotifierCommandResponse
type WorkspaceNotifierCommandResponse struct {
	Command   WorkspaceNotifierCommandAction `json:"command"`
	ProcessId string                         `json:"process_id"`
}

// NewWorkspaceNotifierCommandResponse instantiates a new WorkspaceNotifierCommandResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceNotifierCommandResponse(command WorkspaceNotifierCommandAction, processId string) *WorkspaceNotifierCommandResponse {
	this := WorkspaceNotifierCommandResponse{}
	this.Command = command
	this.ProcessId = processId
	return &this
}

// NewWorkspaceNotifierCommandResponseWithDefaults instantiates a new WorkspaceNotifierCommandResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceNotifierCommandResponseWithDefaults() *WorkspaceNotifierCommandResponse {
	this := WorkspaceNotifierCommandResponse{}
	return &this
}

// GetCommand returns the Command field value
func (o *WorkspaceNotifierCommandResponse) GetCommand() WorkspaceNotifierCommandAction {
	if o == nil {
		var ret WorkspaceNotifierCommandAction
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *WorkspaceNotifierCommandResponse) GetCommandOk() (*WorkspaceNotifierCommandAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *WorkspaceNotifierCommandResponse) SetCommand(v WorkspaceNotifierCommandAction) {
	o.Command = v
}

// GetProcessId returns the ProcessId field value
func (o *WorkspaceNotifierCommandResponse) GetProcessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceNotifierCommandResponse) GetProcessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessId, true
}

// SetProcessId sets field value
func (o *WorkspaceNotifierCommandResponse) SetProcessId(v string) {
	o.ProcessId = v
}

func (o WorkspaceNotifierCommandResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["command"] = o.Command
	}
	if true {
		toSerialize["process_id"] = o.ProcessId
	}
	return json.Marshal(toSerialize)
}

type NullableWorkspaceNotifierCommandResponse struct {
	value *WorkspaceNotifierCommandResponse
	isSet bool
}

func (v NullableWorkspaceNotifierCommandResponse) Get() *WorkspaceNotifierCommandResponse {
	return v.value
}

func (v *NullableWorkspaceNotifierCommandResponse) Set(val *WorkspaceNotifierCommandResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceNotifierCommandResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceNotifierCommandResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceNotifierCommandResponse(val *WorkspaceNotifierCommandResponse) *NullableWorkspaceNotifierCommandResponse {
	return &NullableWorkspaceNotifierCommandResponse{value: val, isSet: true}
}

func (v NullableWorkspaceNotifierCommandResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceNotifierCommandResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
