/*
Turbot Pipes

Turbot Pipes is an intelligence, automation & security platform built specifically for DevOps.

API version: {{OPEN_API_VERSION}}
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipes

import (
	"encoding/json"
	"fmt"
)

// DatatankPartCmd the model 'DatatankPartCmd'
type DatatankPartCmd string

// List of DatatankPartCmd
const (
	DtpcRefresh DatatankPartCmd = "refresh"
)

// All allowed values of DatatankPartCmd enum
var AllowedDatatankPartCmdEnumValues = []DatatankPartCmd{
	"refresh",
}

func (v *DatatankPartCmd) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DatatankPartCmd(value)
	for _, existing := range AllowedDatatankPartCmdEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DatatankPartCmd", value)
}

// NewDatatankPartCmdFromValue returns a pointer to a valid DatatankPartCmd
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDatatankPartCmdFromValue(v string) (*DatatankPartCmd, error) {
	ev := DatatankPartCmd(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DatatankPartCmd: valid values are %v", v, AllowedDatatankPartCmdEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DatatankPartCmd) IsValid() bool {
	for _, existing := range AllowedDatatankPartCmdEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DatatankPartCmd value
func (v DatatankPartCmd) Ptr() *DatatankPartCmd {
	return &v
}

type NullableDatatankPartCmd struct {
	value *DatatankPartCmd
	isSet bool
}

func (v NullableDatatankPartCmd) Get() *DatatankPartCmd {
	return v.value
}

func (v *NullableDatatankPartCmd) Set(val *DatatankPartCmd) {
	v.value = val
	v.isSet = true
}

func (v NullableDatatankPartCmd) IsSet() bool {
	return v.isSet
}

func (v *NullableDatatankPartCmd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatatankPartCmd(val *DatatankPartCmd) *NullableDatatankPartCmd {
	return &NullableDatatankPartCmd{value: val, isSet: true}
}

func (v NullableDatatankPartCmd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatatankPartCmd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
